In [2]:
import pandas as pd
import numpy as np

In [4]:
f=pd.read_csv("/root/public/VE450capstone_beamTracking/data/dev_dataset_csv/train_set.csv", engine='python')

In [85]:
len(f)

281100

In [86]:
f.head()

,Beam 1,Beam 2,Beam 3,Beam 4,Beam 5,Beam 6,Beam 7,Beam 8,Beam 9,Beam 10,...,Img Path 4,Img Path 5,Img Path 6,Img Path 7,Img Path 8,Img Path 9,Img Path 10,Img Path 11,Img Path 12,Img Path 13
0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,...,visual_data\instance565\cam1.jpg,visual_data\instance566\cam1.jpg,visual_data\instance567\cam1.jpg,visual_data\instance568\cam1.jpg,visual_data\instance569\cam1.jpg,visual_data\instance570\cam1.jpg,visual_data\instance571\cam1.jpg,visual_data\instance572\cam1.jpg,visual_data\instance573\cam1.jpg,visual_data\instance574\cam1.jpg
1,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,...,visual_data\instance567\cam1.jpg,visual_data\instance568\cam1.jpg,visual_data\instance569\cam1.jpg,visual_data\instance570\cam1.jpg,visual_data\instance571\cam1.jpg,visual_data\instance572\cam1.jpg,visual_data\instance573\cam1.jpg,visual_data\instance574\cam1.jpg,visual_data\instance575\cam1.jpg,visual_data\instance576\cam1.jpg
2,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,...,visual_data\instance568\cam1.jpg,visual_data\instance569\cam1.jpg,visual_data\instance570\cam1.jpg,visual_data\instance571\cam1.jpg,visual_data\instance572\cam1.jpg,visual_data\instance573\cam1.jpg,visual_data\instance574\cam1.jpg,visual_data\instance575\cam1.jpg,visual_data\instance576\cam1.jpg,visual_data\instance577\cam1.jpg
3,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,...,visual_data\instance569\cam1.jpg,visual_data\instance570\cam1.jpg,visual_data\instance571\cam1.jpg,visual_data\instance572\cam1.jpg,visual_data\instance573\cam1.jpg,visual_data\instance574\cam1.jpg,visual_data\instance575\cam1.jpg,visual_data\instance576\cam1.jpg,visual_data\instance577\cam1.jpg,visual_data\instance578\cam1.jpg
4,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,...,visual_data\instance570\cam1.jpg,visual_data\instance571\cam1.jpg,visual_data\instance572\cam1.jpg,visual_data\instance573\cam1.jpg,visual_data\instance574\cam1.jpg,visual_data\instance575\cam1.jpg,visual_data\instance576\cam1.jpg,visual_data\instance577\cam1.jpg,visual_data\instance578\cam1.jpg,visual_data\instance579\cam1.jpg

In [87]:
f.tail()

,Beam 1,Beam 2,Beam 3,Beam 4,Beam 5,Beam 6,Beam 7,Beam 8,Beam 9,Beam 10,...,Img Path 4,Img Path 5,Img Path 6,Img Path 7,Img Path 8,Img Path 9,Img Path 10,Img Path 11,Img Path 12,Img Path 13
281095,105.0,105.0,104.0,104.0,104.0,103.0,103.0,102.0,102.0,101.0,...,visual_data\instance3981\cam6.jpg,visual_data\instance3982\cam6.jpg,visual_data\instance3983\cam6.jpg,visual_data\instance3984\cam6.jpg,visual_data\instance3985\cam6.jpg,visual_data\instance3986\cam6.jpg,visual_data\instance3987\cam5.jpg,visual_data\instance3988\cam5.jpg,visual_data\instance3989\cam5.jpg,visual_data\instance3990\cam5.jpg
281096,105.0,104.0,104.0,104.0,103.0,103.0,102.0,102.0,101.0,101.0,...,visual_data\instance3982\cam6.jpg,visual_data\instance3983\cam6.jpg,visual_data\instance3984\cam6.jpg,visual_data\instance3985\cam6.jpg,visual_data\instance3986\cam6.jpg,visual_data\instance3987\cam5.jpg,visual_data\instance3988\cam5.jpg,visual_data\instance3989\cam5.jpg,visual_data\instance3990\cam5.jpg,visual_data\instance3991\cam5.jpg
281097,104.0,104.0,104.0,103.0,103.0,102.0,102.0,101.0,101.0,100.0,...,visual_data\instance3983\cam6.jpg,visual_data\instance3984\cam6.jpg,visual_data\instance3985\cam6.jpg,visual_data\instance3986\cam6.jpg,visual_data\instance3987\cam5.jpg,visual_data\instance3988\cam5.jpg,visual_data\instance3989\cam5.jpg,visual_data\instance3990\cam5.jpg,visual_data\instance3991\cam5.jpg,visual_data\instance3992\cam5.jpg
281098,104.0,103.0,103.0,102.0,102.0,101.0,101.0,100.0,100.0,99.0,...,visual_data\instance3985\cam6.jpg,visual_data\instance3986\cam6.jpg,visual_data\instance3987\cam5.jpg,visual_data\instance3988\cam5.jpg,visual_data\instance3989\cam5.jpg,visual_data\instance3990\cam5.jpg,visual_data\instance3991\cam5.jpg,visual_data\instance3992\cam5.jpg,visual_data\instance3993\cam5.jpg,visual_data\instance3994\cam5.jpg
281099,103.0,102.0,102.0,101.0,101.0,100.0,100.0,99.0,99.0,98.0,...,visual_data\instance3987\cam5.jpg,visual_data\instance3988\cam5.jpg,visual_data\instance3989\cam5.jpg,visual_data\instance3990\cam5.jpg,visual_data\instance3991\cam5.jpg,visual_data\instance3992\cam5.jpg,visual_data\instance3993\cam5.jpg,visual_data\instance3994\cam5.jpg,visual_data\instance3995\cam5.jpg,visual_data\instance3996\cam5.jpg

In [88]:
f[0:1].loc[0]

Beam 1                                      124
Beam 2                                      124
Beam 3                                      124
Beam 4                                      124
Beam 5                                      124
Beam 6                                      124
Beam 7                                      124
Beam 8                                      124
Beam 9                                      124
Beam 10                                     124
Beam 11                                     124
Beam 12                                     124
Beam 13                                     124
Img Path 1     visual_data\instance562\cam1.jpg
Img Path 2     visual_data\instance563\cam1.jpg
Img Path 3     visual_data\instance564\cam1.jpg
Img Path 4     visual_data\instance565\cam1.jpg
Img Path 5     visual_data\instance566\cam1.jpg
Img Path 6     visual_data\instance567\cam1.jpg
Img Path 7     visual_data\instance568\cam1.jpg
Img Path 8     visual_data\instance569\cam1.jpg
Img Path 9     visual_data\instance570\cam1.jpg
Img Path 10    visual_data\instance571\cam1.jpg
Img Path 11    visual_data\instance572\cam1.jpg
Img Path 12    visual_data\instance573\cam1.jpg
Img Path 13    visual_data\instance574\cam1.jpg
Name: 0, dtype: object

In [89]:
f[1:2].loc[1]

Beam 1                                      124
Beam 2                                      124
Beam 3                                      124
Beam 4                                      124
Beam 5                                      124
Beam 6                                      124
Beam 7                                      124
Beam 8                                      124
Beam 9                                      124
Beam 10                                     124
Beam 11                                     124
Beam 12                                     124
Beam 13                                     124
Img Path 1     visual_data\instance564\cam1.jpg
Img Path 2     visual_data\instance565\cam1.jpg
Img Path 3     visual_data\instance566\cam1.jpg
Img Path 4     visual_data\instance567\cam1.jpg
Img Path 5     visual_data\instance568\cam1.jpg
Img Path 6     visual_data\instance569\cam1.jpg
Img Path 7     visual_data\instance570\cam1.jpg
Img Path 8     visual_data\instance571\cam1.jpg
Img Path 9     visual_data\instance572\cam1.jpg
Img Path 10    visual_data\instance573\cam1.jpg
Img Path 11    visual_data\instance574\cam1.jpg
Img Path 12    visual_data\instance575\cam1.jpg
Img Path 13    visual_data\instance576\cam1.jpg
Name: 1, dtype: object

In [90]:
f[2:3].loc[2]

Beam 1                                      124
Beam 2                                      124
Beam 3                                      124
Beam 4                                      124
Beam 5                                      124
Beam 6                                      124
Beam 7                                      124
Beam 8                                      124
Beam 9                                      124
Beam 10                                     124
Beam 11                                     124
Beam 12                                     124
Beam 13                                     125
Img Path 1     visual_data\instance565\cam1.jpg
Img Path 2     visual_data\instance566\cam1.jpg
Img Path 3     visual_data\instance567\cam1.jpg
Img Path 4     visual_data\instance568\cam1.jpg
Img Path 5     visual_data\instance569\cam1.jpg
Img Path 6     visual_data\instance570\cam1.jpg
Img Path 7     visual_data\instance571\cam1.jpg
Img Path 8     visual_data\instance572\cam1.jpg
Img Path 9     visual_data\instance573\cam1.jpg
Img Path 10    visual_data\instance574\cam1.jpg
Img Path 11    visual_data\instance575\cam1.jpg
Img Path 12    visual_data\instance576\cam1.jpg
Img Path 13    visual_data\instance577\cam1.jpg
Name: 2, dtype: object

In [91]:
f[1:2].loc[1].tolist()[:13]

[124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0]

In [5]:
def instanceIndex(row):
    for i in range(13,26):
        k=j=row[i].find("instance")+len("instance")
        while row[i][k].isnumeric():
            k+=1
        row[i]=row[i][j:k]

In [6]:
prev=f[0:1].loc[0].tolist()
# instanceIndex(prev)
prev

[124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 124.0,
 'visual_data\\instance562\\cam1.jpg',
 'visual_data\\instance563\\cam1.jpg',
 'visual_data\\instance564\\cam1.jpg',
 'visual_data\\instance565\\cam1.jpg',
 'visual_data\\instance566\\cam1.jpg',
 'visual_data\\instance567\\cam1.jpg',
 'visual_data\\instance568\\cam1.jpg',
 'visual_data\\instance569\\cam1.jpg',
 'visual_data\\instance570\\cam1.jpg',
 'visual_data\\instance571\\cam1.jpg',
 'visual_data\\instance572\\cam1.jpg',
 'visual_data\\instance573\\cam1.jpg',
 'visual_data\\instance574\\cam1.jpg']

In [7]:
angle=[]
image=[]
prev=f[0:1].loc[0].tolist()
# instanceIndex(prev)

angle.extend(prev[:13])
image.extend(prev[13:])

for i in range(1,len(f)):
#     for i in range(1,len(f)):
    next=f[i:i+1].loc[i].tolist()
#     instanceIndex(next)
    
    increment=0
    for j in range(25,12,-1):
        if next[j]!=prev[j+increment]:
#             print(next[j],prev[j+increment])
            increment+=1
            continue
    
    for j in range(12-increment,-1,-1):
        assert(next[j]==prev[j+increment])
    
    angle.extend(next[13-increment:13])
    image.extend(next[26-increment:])
        
#     print(increment)
    prev=next

In [10]:
print(len(angle))
assert(len(angle)==len(image))

408241

In [15]:
an2 = pd.DataFrame({"angle":angle,"image":image})

In [16]:
an2.to_csv("col2clean.csv")

In [8]:
ans=pd.DataFrame(data=[angle,image])

In [9]:
ans.to_csv("slidingWindow.csv")